[[Aria2]]
arch = "aarch64"
git-tree-sha1 = "0dae7b113417ee4bd7e8b01ce385503ccd20473f"
os = "macos"

    [[Aria2.download]]
    sha256 = "d75c5faa57e9a5a7f45478c3b7440e96f0959c9479172eced816ff7a7b5e980e"
    url = "https://github.com/JuliaBinaryWrappers/Aria2_jll.jl/releases/download/Aria2-v1.37.0+0/Aria2.v1.37.0.aarch64-apple-darwin.tar.gz"
[[Aria2]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d94c9337449df55e10d3801f89a42a8bd9471776"
libc = "glibc"
os = "linux"

    [[Aria2.download]]
    sha256 = "ec6402a4ffa3b7eb039efcfedb9385d1df992488e7c9001189dfbe978ce70caa"
    url = "https://github.com/JuliaBinaryWrappers/Aria2_jll.jl/releases/download/Aria2-v1.37.0+0/Aria2.v1.37.0.aarch64-linux-gnu-cxx03.tar.gz"
[[Aria2]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "26df413b69071bf024b699608dbf5a1f8efa8832"
libc = "glibc"
os = "linux"

    [[Aria2.download]]
    sha256 = "17c143d984740917971592b78f09f4a54cbf6bc31aa9f2a927d38391bddd1b60"
    url = "https://github.com/JuliaBinaryWrappers/Aria2_jll.jl/releases/download/Aria2-v1.37.0+0/Aria2.v1.37.0.aarch64-linux-gnu-cxx11.tar.gz"
[[Aria2]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bdf6ae672feb94f5abf31a261abcb23f9651bfd8"
libc = "musl"
os = "linux"

    [[Aria2.download]]
    sha256 = "265540ed8613fde603a8202f78f970f7f1c589c58e0df62276f24f4973617879"
    url = "https://github.com/JuliaBinaryWrappers/Aria2_jll.jl/releases/download/Aria2-v1.37.0+0/Aria2.v1.37.0.aarch64-linux-musl-cxx03.tar.gz"
[[Aria2]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b9802befc0297ed24b58f58b2d58790ac9d39b65"
libc = "musl"
os = "linux"

    [[Aria2.download]]
    sha256 = "8053d714f3ecefa411b7fa47f65919dad9938c4e3115c54d16cd83a8aa47288e"
    url = "https://github.com/JuliaBinaryWrappers/Aria2_jll.jl/releases/download/Aria2-v1.37.0+0/Aria2.v1.37.0.aarch64-linux-musl-cxx11.tar.gz"
[[Aria2]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c53110228b3323e90047805748bff307e93ecb83"
libc = "glibc"
os = "linux"

    [[Aria2.download]]
    sha256 = "1e5516b47496862d2a47a920da337aee1c75fef10b1d4d8cf7ff7cb86d9723b5"
    url = "https://github.com/JuliaBinaryWrappers/Aria2_jll.jl/releases/download/Aria2-v1.37.0+0/Aria2.v1.37.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Aria2]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c310409f6742ee751f4422da7947be6f0d07e6f2"
libc = "glibc"
os = "linux"

    [[Aria2.download]]
    sha256 = "dc5a69faa03168a685bc431f1a8ac2550dac1b07422c0b0f0db672196e0be07b"
    url = "https://github.com/JuliaBinaryWrappers/Aria2_jll.jl/releases/download/Aria2-v1.37.0+0/Aria2.v1.37.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Aria2]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b612125ab91cb0340de4dc2a4108b95351379515"
libc = "musl"
os = "linux"

    [[Aria2.download]]
    sha256 = "a6a71c75c54913122f092cf6f724aecadced13422abfec1ef260e15d61e31968"
    url = "https://github.com/JuliaBinaryWrappers/Aria2_jll.jl/releases/download/Aria2-v1.37.0+0/Aria2.v1.37.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Aria2]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6d6df2b1e6065b90b7a2cae645ef37e4c636e156"
libc = "musl"
os = "linux"

    [[Aria2.download]]
    sha256 = "5f5ce51ff99d20f409a8b01acb7bf515979a2c9a706f46f28dc8e2cdd6194758"
    url = "https://github.com/JuliaBinaryWrappers/Aria2_jll.jl/releases/download/Aria2-v1.37.0+0/Aria2.v1.37.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Aria2]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "10978b5a8521d07e042909d1fed19709eab91057"
libc = "glibc"
os = "linux"

    [[Aria2.download]]
    sha256 = "24c076996b734c4bdccf061d993e074f13ce41d7fc0d6b8e7982debefbb4149a"
    url = "https://github.com/JuliaBinaryWrappers/Aria2_jll.jl/releases/download/Aria2-v1.37.0+0/Aria2.v1.37.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Aria2]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "da8b9e03943940d9eff5b5018088a623ae3b479c"
libc = "glibc"
os = "linux"

    [[Aria2.download]]
    sha256 = "74c11c551980c6f05874866db4c5c938e17faaa14d1eecce137e0ab4419a6d50"
    url = "https://github.com/JuliaBinaryWrappers/Aria2_jll.jl/releases/download/Aria2-v1.37.0+0/Aria2.v1.37.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Aria2]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e6f5d2d6628361c23ec1ece09cf021e99e8a4348"
libc = "musl"
os = "linux"

    [[Aria2.download]]
    sha256 = "78dd02a0bdbd2ea4cd685a4e82f8abc800f5e55599460ab44a9b8ac13f75dc31"
    url = "https://github.com/JuliaBinaryWrappers/Aria2_jll.jl/releases/download/Aria2-v1.37.0+0/Aria2.v1.37.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Aria2]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b773f3b6dd2ff7d41abaa3f8f8d527e28a3e250c"
libc = "musl"
os = "linux"

    [[Aria2.download]]
    sha256 = "bc7c47655949621e9d4edac0c29d32664eaf7f830dc763669188e91ef47408d3"
    url = "https://github.com/JuliaBinaryWrappers/Aria2_jll.jl/releases/download/Aria2-v1.37.0+0/Aria2.v1.37.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Aria2]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5a46b6029215e405f0216f2443e03a526b513d69"
libc = "glibc"
os = "linux"

    [[Aria2.download]]
    sha256 = "70d6d3b6a0c305e393c2c65867d49899b3b3aeef8d712b6c2a25c99cbc2365a8"
    url = "https://github.com/JuliaBinaryWrappers/Aria2_jll.jl/releases/download/Aria2-v1.37.0+0/Aria2.v1.37.0.i686-linux-gnu-cxx03.tar.gz"
[[Aria2]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "04155a9e68d64b0d2cfadcb627d0a17e9531fcb6"
libc = "glibc"
os = "linux"

    [[Aria2.download]]
    sha256 = "eec2fe96cab6b4ba1103ac2ecf8277ef15e1f96eaebc01ff83837fd2645122ba"
    url = "https://github.com/JuliaBinaryWrappers/Aria2_jll.jl/releases/download/Aria2-v1.37.0+0/Aria2.v1.37.0.i686-linux-gnu-cxx11.tar.gz"
[[Aria2]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b7c43ecab1a5190fbdd5d47b0b65010401696a84"
libc = "musl"
os = "linux"

    [[Aria2.download]]
    sha256 = "d9efcd17361f51a1aaab3146c78471f8b611a7b7987bab26420297de6be41abd"
    url = "https://github.com/JuliaBinaryWrappers/Aria2_jll.jl/releases/download/Aria2-v1.37.0+0/Aria2.v1.37.0.i686-linux-musl-cxx03.tar.gz"
[[Aria2]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "55231101f5774ef0f13625ac7d76340f8d24fc6d"
libc = "musl"
os = "linux"

    [[Aria2.download]]
    sha256 = "896c34a762282cebbdada7631910f2349ffa7851086fbfda419b9c1929806a4d"
    url = "https://github.com/JuliaBinaryWrappers/Aria2_jll.jl/releases/download/Aria2-v1.37.0+0/Aria2.v1.37.0.i686-linux-musl-cxx11.tar.gz"
[[Aria2]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "733235af02d9e2950cf8be104af227fb14b1c800"
os = "windows"

    [[Aria2.download]]
    sha256 = "3ae7f9a16ff4d7248f6e6dd56c09b176bb9b60854c13d565f82aa7ddd1825abf"
    url = "https://github.com/JuliaBinaryWrappers/Aria2_jll.jl/releases/download/Aria2-v1.37.0+0/Aria2.v1.37.0.i686-w64-mingw32-cxx03.tar.gz"
[[Aria2]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c3df3585fb73492a4a53f1cc448d44b87e36fe85"
os = "windows"

    [[Aria2.download]]
    sha256 = "4ba7c52b227c4fdb3594cc574d7a0643c821be4dd5e14108ff4808af6aea61ee"
    url = "https://github.com/JuliaBinaryWrappers/Aria2_jll.jl/releases/download/Aria2-v1.37.0+0/Aria2.v1.37.0.i686-w64-mingw32-cxx11.tar.gz"
[[Aria2]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d48e784165a677a4a65041bd2b5304b56b5be26b"
libc = "glibc"
os = "linux"

    [[Aria2.download]]
    sha256 = "a498a74979581445f02cde652bfee69b91b29d5dab9e2aebe13ec80b4531ee96"
    url = "https://github.com/JuliaBinaryWrappers/Aria2_jll.jl/releases/download/Aria2-v1.37.0+0/Aria2.v1.37.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Aria2]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2373d4579307364b1663ac5d3a3be12cd8b69c2c"
libc = "glibc"
os = "linux"

    [[Aria2.download]]
    sha256 = "70924cf4838cc0df7501879353e95a74e0d233a3272f461470d3ec1ae3e4237a"
    url = "https://github.com/JuliaBinaryWrappers/Aria2_jll.jl/releases/download/Aria2-v1.37.0+0/Aria2.v1.37.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Aria2]]
arch = "x86_64"
git-tree-sha1 = "8f9482b08ab3a4f8d2f6bf9b02b5f3b3a06a8032"
os = "macos"

    [[Aria2.download]]
    sha256 = "fc6753627b5e9eb52232e834c58c6d00923b17e3d948a32d650c74b4441bee83"
    url = "https://github.com/JuliaBinaryWrappers/Aria2_jll.jl/releases/download/Aria2-v1.37.0+0/Aria2.v1.37.0.x86_64-apple-darwin.tar.gz"
[[Aria2]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "94489a58ff0e057f3c79cbdafb65e3256eef1d6e"
libc = "glibc"
os = "linux"

    [[Aria2.download]]
    sha256 = "7de0e35e3a256049d85b1ce88ccc1d354b93b6882a80c7b77b3a5552ea3e8eed"
    url = "https://github.com/JuliaBinaryWrappers/Aria2_jll.jl/releases/download/Aria2-v1.37.0+0/Aria2.v1.37.0.x86_64-linux-gnu-cxx03.tar.gz"
[[Aria2]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3b5b1c766502841c7a230f2e93d9070003abe584"
libc = "glibc"
os = "linux"

    [[Aria2.download]]
    sha256 = "2609ecf20abfcb21e4d2ca19c000b4a41ef054729eb40f5b4c99c7c556bd7b9a"
    url = "https://github.com/JuliaBinaryWrappers/Aria2_jll.jl/releases/download/Aria2-v1.37.0+0/Aria2.v1.37.0.x86_64-linux-gnu-cxx11.tar.gz"
[[Aria2]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "900f4fb770c00d52dd80935b7c9310ca07fdddf8"
libc = "musl"
os = "linux"

    [[Aria2.download]]
    sha256 = "9bcaed7cc1c3c9d18eea7e0643d6f1fc23b65bb69b08413bc724cac9f25c6a59"
    url = "https://github.com/JuliaBinaryWrappers/Aria2_jll.jl/releases/download/Aria2-v1.37.0+0/Aria2.v1.37.0.x86_64-linux-musl-cxx03.tar.gz"
[[Aria2]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bb40b768faae98bcdf97daa602aed5367225f510"
libc = "musl"
os = "linux"

    [[Aria2.download]]
    sha256 = "470cc049433f8da1e0c74cf0662e51f651e1ea39285491be6e7ad9d46a2b03e8"
    url = "https://github.com/JuliaBinaryWrappers/Aria2_jll.jl/releases/download/Aria2-v1.37.0+0/Aria2.v1.37.0.x86_64-linux-musl-cxx11.tar.gz"
[[Aria2]]
arch = "x86_64"
git-tree-sha1 = "0138a156305c25f437545698623f624a4a313cb3"
os = "freebsd"

    [[Aria2.download]]
    sha256 = "d6f70a73f4ff71aa57fe8d2279fecd64afd39f8d4460e25ec3b6dccbae8fd8e1"
    url = "https://github.com/JuliaBinaryWrappers/Aria2_jll.jl/releases/download/Aria2-v1.37.0+0/Aria2.v1.37.0.x86_64-unknown-freebsd.tar.gz"
[[Aria2]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ba3a68fe817452352780c85f47904b2e9d063b59"
os = "windows"

    [[Aria2.download]]
    sha256 = "29dff06a9593a3cc28f6af9f320acbd896fec58e0413a10454520e39d49cd77a"
    url = "https://github.com/JuliaBinaryWrappers/Aria2_jll.jl/releases/download/Aria2-v1.37.0+0/Aria2.v1.37.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[Aria2]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "68ae9427830590f74fcbcba953a0e53170025dee"
os = "windows"

    [[Aria2.download]]
    sha256 = "aaca7b9550ca8fc67f724dc6321add12f2fa18dc590dbc9d0b252fd7808d0665"
    url = "https://github.com/JuliaBinaryWrappers/Aria2_jll.jl/releases/download/Aria2-v1.37.0+0/Aria2.v1.37.0.x86_64-w64-mingw32-cxx11.tar.gz"
