[[Aria2]]
arch = "aarch64"
git-tree-sha1 = "fbcbe14df3b03a411db8720b3a2ec5918f7ec26d"
os = "macos"

    [[Aria2.download]]
    sha256 = "ce3b6afb17d09aa3efe07c9e44edf64fc22c55bd0f55e09899fc65b61eb83270"
    url = "https://github.com/JuliaBinaryWrappers/Aria2_jll.jl/releases/download/Aria2-v1.36.0+1/Aria2.v1.36.0.aarch64-apple-darwin.tar.gz"
[[Aria2]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0ec923686d0e4f6745eb9c1f28475ecec9c86183"
libc = "glibc"
os = "linux"

    [[Aria2.download]]
    sha256 = "67a01cdb9a14ce8ff84aef2bd2fdfabdfdb033f353929cd1920f4ff62abc9991"
    url = "https://github.com/JuliaBinaryWrappers/Aria2_jll.jl/releases/download/Aria2-v1.36.0+1/Aria2.v1.36.0.aarch64-linux-gnu-cxx03.tar.gz"
[[Aria2]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1d3fa1056d1f9e3c5f0d7d4cfffa6709881460db"
libc = "glibc"
os = "linux"

    [[Aria2.download]]
    sha256 = "ac86ca3f215fc4496fb1d64df02bd9858b1b0018550d89e29b027e5b2a131062"
    url = "https://github.com/JuliaBinaryWrappers/Aria2_jll.jl/releases/download/Aria2-v1.36.0+1/Aria2.v1.36.0.aarch64-linux-gnu-cxx11.tar.gz"
[[Aria2]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0065abeaa9944dcd0df6bcff8c1eae2fa178af54"
libc = "musl"
os = "linux"

    [[Aria2.download]]
    sha256 = "741c9f83d6132fa9b7c2e078a557418e2bfa2f0d4a43955c8ea655df05a64035"
    url = "https://github.com/JuliaBinaryWrappers/Aria2_jll.jl/releases/download/Aria2-v1.36.0+1/Aria2.v1.36.0.aarch64-linux-musl-cxx03.tar.gz"
[[Aria2]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "239f0da51e313ac5cfc2ee9e68a1a4b4b3c66657"
libc = "musl"
os = "linux"

    [[Aria2.download]]
    sha256 = "ecf6c17b7f72653c20fadc46dcf6ed25f488830930271e3676e4eea759dfdafc"
    url = "https://github.com/JuliaBinaryWrappers/Aria2_jll.jl/releases/download/Aria2-v1.36.0+1/Aria2.v1.36.0.aarch64-linux-musl-cxx11.tar.gz"
[[Aria2]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6ee50156f4d56f99b92401e5f3a53460960eb616"
libc = "glibc"
os = "linux"

    [[Aria2.download]]
    sha256 = "78e57c136aab05ade329d8d648dce88bc0014ee6189fd1386a3b6636f2bd623b"
    url = "https://github.com/JuliaBinaryWrappers/Aria2_jll.jl/releases/download/Aria2-v1.36.0+1/Aria2.v1.36.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Aria2]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "19e99954214ffc31b5c0d19c62686984c08cdd7a"
libc = "glibc"
os = "linux"

    [[Aria2.download]]
    sha256 = "3285403ff8a951fe40b012a2c9fe3d3620906cd66c247f9556ef27fed39c93ed"
    url = "https://github.com/JuliaBinaryWrappers/Aria2_jll.jl/releases/download/Aria2-v1.36.0+1/Aria2.v1.36.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Aria2]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d0a05f9c0e971c0438854c98c5a93da70ce844bf"
libc = "musl"
os = "linux"

    [[Aria2.download]]
    sha256 = "4d7aa3ae7d9ccf1549e73435b3c1c0e6ac00f0d07f68befb04dbd99aabec962f"
    url = "https://github.com/JuliaBinaryWrappers/Aria2_jll.jl/releases/download/Aria2-v1.36.0+1/Aria2.v1.36.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Aria2]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8ce5bd8322528d87724d3833719f538f4d3cd7a8"
libc = "musl"
os = "linux"

    [[Aria2.download]]
    sha256 = "5345c1e3184a0fbffd97a11b88412cfb627016e4565b55ee925577c45f6f6d78"
    url = "https://github.com/JuliaBinaryWrappers/Aria2_jll.jl/releases/download/Aria2-v1.36.0+1/Aria2.v1.36.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Aria2]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6d6e2b5f685e020111b86e678bde181d02928fb0"
libc = "glibc"
os = "linux"

    [[Aria2.download]]
    sha256 = "eeb312fc163058cf1744031d80a13b6298ac27cd3f20f16261df7a0808873d88"
    url = "https://github.com/JuliaBinaryWrappers/Aria2_jll.jl/releases/download/Aria2-v1.36.0+1/Aria2.v1.36.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Aria2]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c25358eef9e490e79806a84f06e859789b63b062"
libc = "glibc"
os = "linux"

    [[Aria2.download]]
    sha256 = "c48576c62c392f7e15fbca3fc8cbb97cea5ef80bb9b6cb311229c03f1141d071"
    url = "https://github.com/JuliaBinaryWrappers/Aria2_jll.jl/releases/download/Aria2-v1.36.0+1/Aria2.v1.36.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Aria2]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "37aedf969afffb2713a37614b6df6f52261a7bfa"
libc = "musl"
os = "linux"

    [[Aria2.download]]
    sha256 = "7f3a6981d6d7ee670d68308096bb934f3097bf21fab0e45bbf72d0a4bb9d69a3"
    url = "https://github.com/JuliaBinaryWrappers/Aria2_jll.jl/releases/download/Aria2-v1.36.0+1/Aria2.v1.36.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Aria2]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c81b1c280e7a2178ba7a619b1a2f33de97168603"
libc = "musl"
os = "linux"

    [[Aria2.download]]
    sha256 = "efdc5c239e8167705065ee8edfe36ae4c7584133f2daaf11baf2e991167b4f04"
    url = "https://github.com/JuliaBinaryWrappers/Aria2_jll.jl/releases/download/Aria2-v1.36.0+1/Aria2.v1.36.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Aria2]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3920c35f17b927e599e023eb80e8b07257a506d6"
libc = "glibc"
os = "linux"

    [[Aria2.download]]
    sha256 = "ba117f04e7aa79f0664a33061f737acffa884fa0207008d8279cad2579f610ea"
    url = "https://github.com/JuliaBinaryWrappers/Aria2_jll.jl/releases/download/Aria2-v1.36.0+1/Aria2.v1.36.0.i686-linux-gnu-cxx03.tar.gz"
[[Aria2]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dffa2a18cab8ce8cca620b1a0d5b5a4f0e77a3c5"
libc = "glibc"
os = "linux"

    [[Aria2.download]]
    sha256 = "47f405a0b82047bc43b53282c72e788fcc372e6970ec4f39dd076686df541928"
    url = "https://github.com/JuliaBinaryWrappers/Aria2_jll.jl/releases/download/Aria2-v1.36.0+1/Aria2.v1.36.0.i686-linux-gnu-cxx11.tar.gz"
[[Aria2]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a4de97f67f6e46a6fd68984a1d9e48bdc056d4e9"
libc = "musl"
os = "linux"

    [[Aria2.download]]
    sha256 = "ef99a56f21a16f4b98a268278fc6509568410404c3d8fef90fe20e0ee6d82fa6"
    url = "https://github.com/JuliaBinaryWrappers/Aria2_jll.jl/releases/download/Aria2-v1.36.0+1/Aria2.v1.36.0.i686-linux-musl-cxx03.tar.gz"
[[Aria2]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "98a5d8ace70670fa28157d667d33234b46fde334"
libc = "musl"
os = "linux"

    [[Aria2.download]]
    sha256 = "2adb815a9301318dcec98f5180856f7312156f8d90e363a2f6e5bc31accf8c11"
    url = "https://github.com/JuliaBinaryWrappers/Aria2_jll.jl/releases/download/Aria2-v1.36.0+1/Aria2.v1.36.0.i686-linux-musl-cxx11.tar.gz"
[[Aria2]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d671e40bb9aa3e799141f6aece2b4d4cde57da36"
os = "windows"

    [[Aria2.download]]
    sha256 = "6ccaff050a540ff20627f80da806e4760571f92f9e8f704e6ee1df7a9fcab5e9"
    url = "https://github.com/JuliaBinaryWrappers/Aria2_jll.jl/releases/download/Aria2-v1.36.0+1/Aria2.v1.36.0.i686-w64-mingw32-cxx03.tar.gz"
[[Aria2]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "30103c0f0fada5dd3482cf30122abe08789e9a72"
os = "windows"

    [[Aria2.download]]
    sha256 = "ba96ea2827b09281f2ad980b0ed1910a7f33e7e3e06607acbbaa6ec381511758"
    url = "https://github.com/JuliaBinaryWrappers/Aria2_jll.jl/releases/download/Aria2-v1.36.0+1/Aria2.v1.36.0.i686-w64-mingw32-cxx11.tar.gz"
[[Aria2]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "da5df82d2c3dd470e63d3bc5b362a4c49434791d"
libc = "glibc"
os = "linux"

    [[Aria2.download]]
    sha256 = "ea815398e429c1b89aed27daf62c8f424f64091e9924d3ffa155127ccd71a24a"
    url = "https://github.com/JuliaBinaryWrappers/Aria2_jll.jl/releases/download/Aria2-v1.36.0+1/Aria2.v1.36.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Aria2]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c629b7ca0900b5602963862e5ba86eef51e648e6"
libc = "glibc"
os = "linux"

    [[Aria2.download]]
    sha256 = "ed76d8cf9f5fd1fc56b38e8a52afc178e9caf1beae8a2147fc69f1693c93b1cf"
    url = "https://github.com/JuliaBinaryWrappers/Aria2_jll.jl/releases/download/Aria2-v1.36.0+1/Aria2.v1.36.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Aria2]]
arch = "x86_64"
git-tree-sha1 = "446e52a1b3aa88b070876e2f6d94e7455558fb87"
os = "macos"

    [[Aria2.download]]
    sha256 = "70aa56d22814b8484a0c9db3a14e0daeb08f3bd05e07877579cd7677d2a8cd21"
    url = "https://github.com/JuliaBinaryWrappers/Aria2_jll.jl/releases/download/Aria2-v1.36.0+1/Aria2.v1.36.0.x86_64-apple-darwin.tar.gz"
[[Aria2]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a3f67425e45672e5bd9cf268b5f7f7d71938df4e"
libc = "glibc"
os = "linux"

    [[Aria2.download]]
    sha256 = "bacb91552754ae1eea907dfeda081fe65f2f70a006bb83d6a7ed7c3f9f10578b"
    url = "https://github.com/JuliaBinaryWrappers/Aria2_jll.jl/releases/download/Aria2-v1.36.0+1/Aria2.v1.36.0.x86_64-linux-gnu-cxx03.tar.gz"
[[Aria2]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d693ba78b43d52aa877c0ee18211ba6f3adff0b9"
libc = "glibc"
os = "linux"

    [[Aria2.download]]
    sha256 = "16978f9f91f328e107f135d963cea801a1848526404bc93b7db33f673b90b3e6"
    url = "https://github.com/JuliaBinaryWrappers/Aria2_jll.jl/releases/download/Aria2-v1.36.0+1/Aria2.v1.36.0.x86_64-linux-gnu-cxx11.tar.gz"
[[Aria2]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7036f57a24c5cdb457ee15214ff3b51622e4e1ea"
libc = "musl"
os = "linux"

    [[Aria2.download]]
    sha256 = "cc182add5bbf74f0a8f94d65a1eab3f0ce09250cb5ba5ab933c7887e5cf5e5e2"
    url = "https://github.com/JuliaBinaryWrappers/Aria2_jll.jl/releases/download/Aria2-v1.36.0+1/Aria2.v1.36.0.x86_64-linux-musl-cxx03.tar.gz"
[[Aria2]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a060bab2b7709c086e59ef77d3148e6ad758826a"
libc = "musl"
os = "linux"

    [[Aria2.download]]
    sha256 = "c2eef10f63f9599555cb67d98bd28d04a742be6f0afb4835d5068c0834180744"
    url = "https://github.com/JuliaBinaryWrappers/Aria2_jll.jl/releases/download/Aria2-v1.36.0+1/Aria2.v1.36.0.x86_64-linux-musl-cxx11.tar.gz"
[[Aria2]]
arch = "x86_64"
git-tree-sha1 = "1df0c706ee3ec85970bb646619a1857e71ad6976"
os = "freebsd"

    [[Aria2.download]]
    sha256 = "2ff60e1a207be20741c0a234a26ac7389c5d90b9f9344267718ba65c1c27be16"
    url = "https://github.com/JuliaBinaryWrappers/Aria2_jll.jl/releases/download/Aria2-v1.36.0+1/Aria2.v1.36.0.x86_64-unknown-freebsd.tar.gz"
[[Aria2]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ab92336b9e136036738c6fd6755415147dc4e72c"
os = "windows"

    [[Aria2.download]]
    sha256 = "debd5d08f9086c691493ba7da6613cf844f3d893344dd9ee750e75ca7850ea85"
    url = "https://github.com/JuliaBinaryWrappers/Aria2_jll.jl/releases/download/Aria2-v1.36.0+1/Aria2.v1.36.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[Aria2]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "85d29aba526686ff9050265f84d184062f630748"
os = "windows"

    [[Aria2.download]]
    sha256 = "2b9eeda955cf72ef8da7475e6ccc4f8e84ec9cbe8cbc82a2ca0429fadf6965b7"
    url = "https://github.com/JuliaBinaryWrappers/Aria2_jll.jl/releases/download/Aria2-v1.36.0+1/Aria2.v1.36.0.x86_64-w64-mingw32-cxx11.tar.gz"
